// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHeLiskvXLrAffFiW9gQ04duBGuLiDXrE',
    appId: '1:669375561680:web:244f4ddf6537168a5d83d5',
    messagingSenderId: '669375561680',
    projectId: 'booksapp-94d8f',
    authDomain: 'booksapp-94d8f.firebaseapp.com',
    storageBucket: 'booksapp-94d8f.appspot.com',
    measurementId: 'G-K09NR2GEDR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1-Y4igMOYN_2nnKjN_Lxupj4Tox_gwEU',
    appId: '1:669375561680:android:3b914b61a921aa4a5d83d5',
    messagingSenderId: '669375561680',
    projectId: 'booksapp-94d8f',
    storageBucket: 'booksapp-94d8f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBADBRvbHwGetkEshzmubUsJ73H_0KYuIE',
    appId: '1:669375561680:ios:45bb3ab841592d4a5d83d5',
    messagingSenderId: '669375561680',
    projectId: 'booksapp-94d8f',
    storageBucket: 'booksapp-94d8f.appspot.com',
    iosBundleId: 'com.example.booksApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBADBRvbHwGetkEshzmubUsJ73H_0KYuIE',
    appId: '1:669375561680:ios:45bb3ab841592d4a5d83d5',
    messagingSenderId: '669375561680',
    projectId: 'booksapp-94d8f',
    storageBucket: 'booksapp-94d8f.appspot.com',
    iosBundleId: 'com.example.booksApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHeLiskvXLrAffFiW9gQ04duBGuLiDXrE',
    appId: '1:669375561680:web:c49aea4edd9c1b115d83d5',
    messagingSenderId: '669375561680',
    projectId: 'booksapp-94d8f',
    authDomain: 'booksapp-94d8f.firebaseapp.com',
    storageBucket: 'booksapp-94d8f.appspot.com',
    measurementId: 'G-KV587YSXY9',
  );
}
